default_target: all
.PHONY : default_target

clean:
	cd C:/math/Thesis/Implementations/ResidualConnectivity/RPackage/src/build; \
	MAKE= MAKEFLAGS= "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/nmake.exe" /f  C:/math/Thesis/Implementations/ResidualConnectivity/RPackage/src/build/Makefile clean

all:
	cd C:/math/Thesis/Implementations/ResidualConnectivity/RPackage/src/build; \
	MAKE= MAKEFLAGS= "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/nmake.exe" /f  C:/math/Thesis/Implementations/ResidualConnectivity/RPackage/src/build/Makefile all; \
	MAKE= MAKEFLAGS= "C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/amd64/nmake.exe" /f  C:/math/Thesis/Implementations/ResidualConnectivity/RPackage/src/build/Makefile install
